# If you just need a quick backend for your Symfony application, this is the
# only configuration you must define in this file:
#
# easy_admin:
#     entities:
#         - AppBundle\Entity\Category
#         - AppBundle\Entity\Product
#         - AppBundle\Entity\Purchase
#         - AppBundle\Entity\PurchaseItem
#         - AppBundle\Entity\User
#
# In this demo application, the configuration is split into several small files
# to show an alternative way to define the configuration for complex backends.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://symfony.com/doc/current/bundles/EasyAdminBundle/index.html
#
imports:
    - { resource: easy_admin/ }

easy_admin_extension:
    embedded_list:
        open_new_tab: false

vich_uploader:
    db_driver: orm # or mongodb or phpcr

    mappings:
        default_images:
            uri_prefix: '%ecs.path.default_images%'
            upload_destination: '%kernel.project_dir%/public/%ecs.path.default_images%'
        product_images:
            uri_prefix: '%ecs.path.product_images%'
            upload_destination: '%kernel.project_dir%/public/%ecs.path.product_images%'
        user_contracts:
            uri_prefix: '%ecs.path.user_contracts%'
            upload_destination: '%kernel.project_dir%/public/%ecs.path.user_contracts%'
        blog_covers:
            uri_prefix: '%ecs.path.blog_covers%'
            upload_destination: '%kernel.project_dir%/public/%ecs.path.blog_covers%'

doctrine_migrations:
    dir_name: '%kernel.project_dir%/migrations'
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(LOCAL_DATABASE_URL)%'
                server_version: 'mariadb-10.4.11' # maria db stable
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

            remote:
                # configure these for your database server
                url: '%env(REMOTE_DATABASE_URL)%'
                server_version: '8.0' # mysql 8 community
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        resolve_target_entities:
            Core\Entity\Model\Sluggable: Admin\Entity\AbstractCategory
        mappings:
            Core:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Entity'
                prefix: 'Core\Entity'
                alias: Core
            FrontOffice:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/FrontOffice/Entity'
                prefix: 'FrontOffice\Entity'
                alias: FrontOffice
            Admin:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Admin/Entity'
                prefix: 'Admin\Entity'
                alias: Admin