---
conf:
    os: "10.2"                      # Choose your debian according to bento boxes (need vagrant destroy & vagrant up)
    private_ip: "192.168.56.111"    # VM IP in your host-only-network
    servername: ecoservice.cum     # Servername and domain for your projects
    org: g4-dev                     # Organisation hosting repo
    projectname: ecs                # repo name : src-{{projectname}}
    debug_playbook: false           # !!THIS OPTION ENABLE SHARED FOLDERS!! used to debug playbook
    testing_mode: 0                 # test services
    web_path: www                   # use your own folder
    app_env: dev                    # prod or dev (prod is faster)
    ssl: false                      # disable if you can't install a certificate (not working yet)
    update: yes                      # Update symfony and db
    nfs_force_disable: yes           # don't wan't nfs enabled because it's slow
vm:
    name: ecoservice                # VM name for Virtualbox (string)
    memory: 6144                    # binary friendly value (int)
    cpus: 4                         # logical cores of vm (int)
    cpuexecutioncap: 100             # virtual cpu, use high value with nfs (int | max: 100)
    natdnshostresolver1: "on"       # perf + (string | on/off)
    natdnsproxy1: "on"              # perf + (string | on/off)
    ioapic: "on"                    # perf + (string | on/off)
