# This file sets the configuration of the 'Purchase' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        Purchase:
            class: FrontOffice\Entity\Purchase
            controller: FrontOffice\Controller\Shopping\PurchaseController
            disabled_actions: ['delete']
            label: Vente
            list:
                sort: ['createdAt', 'DESC']
                title: 'Ventes'
                actions: [ { name: 'show', icon: 'shopping-basket' } ]
                fields: ['guid', 'buyer', 'deliveryDate', 'deliveryHour', 'billingAddress', 'purchasedItems', 'total']
            form:
                fields:
                    - { type: 'group', label: 'Delivery Details', icon: 'truck', css_class: 'col-sm-6' }
                    - deliveryDate
                    - deliveryHour
                    - { type: 'group', label: 'Purchase Details', icon: 'shopping-cart', css_class: 'col-sm-6' }
                    - { property: 'guid', type_options: { 'disabled': true } }
                    - { property: 'buyer', type: 'easyadmin_autocomplete' }
                    - { property: 'status', type: choice, type_options: { multiple: false, choices: {'processing': 'processing','shipped': 'shipped' } } }
                    - { type: 'group', label: 'address.shopping', css_class: 'col-sm-6' }
                    - { property: 'shippingAddress', label: 'shipping.informations', type: 'Core\Form\AddressType' }
