easy_admin:
    entities:
        User:
            class: Core\Entity\User
            list:
                title: 'Customers'
                actions: ['-new','show']
                fields:
                - id
                - { property: 'isActive', type: 'boolean', label: 'Active?' }
                - username
                - email
                - purchases
                - { property: 'contract', template: '@admin/custom-fields/contract.html.twig', base_path: '%ecs.path.user_contracts%' }
            show:
                fields:
                - 'id'
                - 'isActive'
                - 'name'
                - 'email'
                - 'purchases'
                - 'companyName'
                - { property: 'isActive', type: 'toggle', label: 'Active?' }
                - { property: 'roles', type: 'array' }
                - { property: 'contract', template: '@admin/custom-fields/contract.html.twig', base_path: '%ecs.path.user_contracts%' }
                - lastLoginAt
                - lastLoginIp
                - lastUserAgent
            form:
                role: ROLE_SUPERADMIN
                fields:
                    - { type: 'group', label: 'Account Information', icon: 'user', css_class: 'col-sm-4' }
                    - { property: 'username' }
                    - { property: 'isActive' }
                    - { type: 'group', label: 'Contact Information', icon: 'envelope-o', css_class: 'col-sm-4' }
                    - { property: 'email' }
                    - { type: 'group', label: 'Legal Information', icon: 'briefcase', css_class: 'col-sm-4' }
                    - { property: 'contractFile', type: 'Vich\UploaderBundle\Form\Type\VichFileType' }
                    - { type: 'group', label: 'Transactions History', icon: 'money', css_class: 'col-sm-12' }
                    - { property: 'purchases', css_class: 'col-sm-12' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true,
                                                                           choices: { 'ROLE_PRO': 'ROLE_PRO', 'ROLE_USER': 'ROLE_USER'}
                    }}
