easy_admin:
    entities:
        CmsCategory:
            class: Admin\Entity\CmsCategory
            label: 'Categories'
            list:
                title: 'Category %%entity_label%%'
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label' }
                    - { property: 'parent', label: 'Parent category' }
                    - 'items'
                    - { property: 'slug', template: '@admin/custom-fields/category-link.html.twig', label: 'links.category', route: 'cmsCategoryList' }

            show:
                fields:
                    - 'id'
                    - { property: 'name', label: 'Label', css_class: 'large' }
                    - { property: 'parent', label: 'Parent category' }
                    - { property: 'items', label: 'Category' }
                    - { property: 'slug', template: '@admin/custom-fields/category-link.html.twig', label: 'links.category', route: 'cmsCategoryList' }
                    - { property: 'image', type: 'image', base_path: '%ecs.path.default_images%' }

            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'name', label: 'Label', css_class: 'large', help: 'As displayed on the website (the slug is auto-generated)' }
                    - { property: 'parent', type: 'easyadmin_autocomplete', label: 'Parent category' }
                    - { property: 'items', type: 'easyadmin_autocomplete', label: 'CmsPages' }
                    - { property: 'imageFile', label: 'Cover', type: 'vich_image', type_options: { required: false } }

                    # if you want to add cmsPages when creating categories, add the 'by_reference' option
                    # - { property: 'cmsPages', type_options: { by_reference: false } }
