# Add pages for the differents spaces here (correspond to webpack entries)
- name: front_office
  pages:
    - homepage
    - accounting
    - compAndDechet
    - recetteDIY
    - diy_list
    - product_category
    - product
    - professional
  default_ext: ts

- name: easyadmin
  pages:
    - js/app

## Options of page entry setter
# - name (config_name)
#   pages:
#      - entry 1 (split assets in different pages)
#   default_ext (by default it's js but typescript is a choice)