imports:
    - { resource: parameters.yaml }
    - { resource: variables.yaml }

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $emailFrom: '%env(MAILER_USER)%'
            $emailName: '%website_name%'

    Core\:
        resource: '../src/Core/*'
        exclude:  '../src/Core/{DependencyInjection,Entity,Tests,Migrations,Kernel.php}'

    core.event_sub:
        class: Core\Event\UserAccountEventSubscriber
        arguments:
            - '$emailFrom'

    core.admin:
        class: Core\Service\AdminService
        public: true

    core.mailer:
        class: Core\Service\MailerService
        public: true

    core.user:
        class: Core\Service\UserService
        public: true

    core.helper.upload_namer:
        class: 'Core\Helper\UploadNamer'
        public: true

    Fixtures\DataFixtures\:
        resource: '../fixtures/DataFixtures'
        tags: ['doctrine.fixture.orm']

    Admin\Controller\:
      resource: '../src/Admin/Controller'
      tags: ['controller.service_arguments']

    FrontOffice\Controller\:
        resource: '../src/FrontOffice/Controller'
        tags: ['controller.service_arguments']

    admin.security.login_form_guard:
        class: 'Admin\Security\LoginFormGuard'

    front_office.security.login_form_guard:
        class: 'FrontOffice\Security\LoginFormGuard'

    Admin\Event\EasyAdminSubscriber\:
        resource: '../src/Admin/Event/EasyAdminSubscriber.php'

    Admin\Repository\:
        resource: '../src/Admin/Repository/*'
        tags: ['doctrine.repository_service']
        public: true

    Admin\Command\InitSettingsCommand:
        arguments:
            - '@doctrine'
            - '%env(MAKE_PATH)%'
        public: true

    fo.select_address.form_type:
        class: FrontOffice\Form\Shopping\SelectAddressType
        autowire: true
        tags: ['form.type']

    FrontOffice\Twig\LoginExtension:
        class: FrontOffice\Twig\LoginExtension
        autowire: true
        tags: ['twig.extension']
