# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'
    # This parameter defines the codes of the locales (languages) enabled in the application
    app_locales: en|es
    app.notifications.email_sender: 69loloro10@gmail.com

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:               # defines the scalar arguments once and apply them to any service defined/created in this file
            $locales: '%app_locales%'
            $defaultLocale: '%locale%'
            $emailSender: '%app.notifications.email_sender%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    Apps\:
        resource: '../src/Apps/*'
        exclude: '../src/Apps/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        tags: ['controller.service_arguments']

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Apps\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    # Ecs\Security:
    #     resource: '../src/Security/*'
    #     tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
