# This file sets the configuration of the main menu. If your backend is simple,
# you probably can leave the 'menu' option empty and rely on the default menu
# created by EasyAdmin.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    design:
        menu:
            - label: 'menu.product'
              icon: 'shopping-basket'
              children:
                  - { entity: 'Product', icon: 'th-list', label: 'menu.product.list', params: { sortField: 'createdAt' }, default: true }
                  - { entity: 'Category', icon: 'tags', label: 'menu.category' }
                  - { entity: 'Product', icon: 'plus-circle', label: 'menu.product.add', params: { action: 'new' } }

            - label: 'menu.blog'
              icon: 'shopping-basket'
              children:
                  - { entity: 'Article', icon: 'th-list', label: 'menu.product.list', params: { sortField: 'createdAt' }, default: true }
            - { label: 'menu.customer', entity: 'User', icon: 'users' }
            - { label: 'menu.admin', entity: 'Admin', icon: 'users' }
            - { label: 'menu.purchase', entity: 'Purchase', icon: 'credit-card', params: { sortField: 'deliveryDate' } }
            - { label: 'menu.about' }

