easy_admin:
    entities:
        Settings:
            class: Admin\Entity\Settings
            label: 'Settings'
            controller: Admin\Controller\SettingsController
            disabled_actions: ['list', 'delete', 'new']

            show:
                fields:
                    - id
                    - 'homeCmsPages'
                    - 'homeDiys'
                    - 'homeProducts'

            form:
                title: 'settings.homepage'
                fields:
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'homeCmsPages', label: 'settings.cmsPages' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'homeDiys', label: 'settings.diy'}
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'homeProducts', label: 'settings.products'}
