name: PHP Composer

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    - name: Install dependencies
      run: composer install -d www/ --no-progress --no-suggest --no-interaction
    
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
